# Generated by Django 5.1.5 on 2025-03-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(default='DEFAULT_SKU', max_length=100, unique=True)),
                ('ean_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('charge_tax', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('size_in', models.CharField(default='Feet', max_length=10)),
                ('length', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True)),
                ('url_handle', models.CharField(blank=True, max_length=255)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerceapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerceapp.product')),
            ],
        ),
    ]
