# Generated by Django 5.0.2 on 2025-03-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Burberry', 'Burberry'), ('Puma', 'Puma'), ('Gucci', 'Gucci'), ('Louis Vuitton', 'Louis Vuitton')], default='Nike', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Beauty', 'Beauty'), ('Toys', 'Toys'), ('Books', 'Books'), ('Sports', 'Sports'), ('Grocery', 'Grocery')], default='clothing', max_length=50),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
