# Generated by Django 5.0.2 on 2025-03-05 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_product_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.AddField(
            model_name='category',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SUB_PARENT_CHOICES', to='ecommerceapp.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home', 'Home'), ('Books', 'Books'), ('Toys', 'Toys')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ecommerceapp.category'),
        ),
    ]
