# Generated by Django 5.0.2 on 2025-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_remove_category_category_type_category_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_parent',
            field=models.CharField(blank=True, choices=[('Smartphones', 'Smartphones'), ('Laptops', 'Laptops'), ('Tablets', 'Tablets'), ('Cameras', 'Cameras'), ('Audio & Headphones', 'Audio & Headphones'), ('Men’s Clothing', 'Men’s Clothing'), ('Women’s Clothing', 'Women’s Clothing'), ('Footwear', 'Footwear'), ('Accessories', 'Accessories'), ('Furniture', 'Furniture'), ('Kitchen Appliances', 'Kitchen Appliances'), ('Home Decor', 'Home Decor'), ('Bedding', 'Bedding'), ('Makeup', 'Makeup'), ('Skincare', 'Skincare'), ('Serums', 'Serums'), ('Hair Care', 'Hair Care'), ('Dolls & Accessories', 'Dolls & Accessories'), ('Action Figures', 'Action Figures'), ('Board Games', 'Board Games'), ('Outdoor Toys', 'Outdoor Toys'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Children’s Books', 'Children’s Books'), ('Educational', 'Educational'), ('Gym Equipment', 'Gym Equipment'), ('Outdoor Sports', 'Outdoor Sports'), ('Fitness Accessories', 'Fitness Accessories'), ('Fruits & Vegetables', 'Fruits & Vegetables'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Dry Fruits, Nuts & Seeds', 'Dry Fruits, Nuts & Seeds')], max_length=255, null=True),
        ),
    ]
