# Generated by Django 5.0.2 on 2025-03-10 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_returneditems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returneditems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='ecommerceapp.order'),
        ),
    ]
