# Generated by Django 5.0.2 on 2025-03-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home', 'Home'), ('Books', 'Books'), ('Toys', 'Toys')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerceapp.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_parent',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Laptops', 'Laptops'), ('Cameras', 'Cameras'), ('Accessories', 'Accessories'), ('Men’s Clothing', 'Men’s Clothing'), ('Women’s Clothing', 'Women’s Clothing'), ('Kids’ Clothing', 'Kids’ Clothing'), ('Footwear', 'Footwear'), ('Furniture', 'Furniture'), ('Decor', 'Decor'), ('Kitchen', 'Kitchen'), ('Appliances', 'Appliances'), ('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), ('Educational', 'Educational'), ('Comics', 'Comics'), ('Soft Toys', 'Soft Toys'), ('Educational Toys', 'Educational Toys'), ('Action Figures', 'Action Figures'), ('Board Games', 'Board Games')], default='Mobiles', max_length=255),
        ),
    ]
