# Generated by Django 5.0.2 on 2025-03-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_alter_category_parent_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_parent',
        ),
        migrations.AddField(
            model_name='category',
            name='category_head',
            field=models.CharField(choices=[('Health & Wellness', 'Health & Wellness'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home', 'Home'), ('Books', 'Books'), ('Toys', 'Toys')], default='Health & Wellness', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='seller_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='media',
            field=models.ImageField(default='Categories/default.jpg', upload_to='Categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
