# Generated by Django 5.0.2 on 2025-03-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_remove_category_sub_parent_category_category_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
