# Generated by Django 5.0.2 on 2025-03-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_brnad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brnad',
            new_name='Brand',
        ),
    ]
