# Generated by Django 5.0.2 on 2025-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_rename_brnad_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner_type', models.CharField(choices=[('Health & Wellness', 'Health & Wellness'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home', 'Home'), ('Books', 'Books'), ('Toys', 'Toys')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
    ]
